module:
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  config: 0
  consumers: 0
  contact: 0
  contextual: 0
  ctools: 0
  datetime: 0
  dblog: 0
  decoupled_router: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  field: 0
  field_ui: 0
  file: 0
  filter: 0
  hal: 0
  help: 0
  history: 0
  image: 0
  jsonapi: 0
  jsonapi_menu_items: 0
  jsonapi_resources: 0
  language: 0
  link: 0
  media: 0
  media_library: 0
  menu_link_content: 0
  menu_ui: 0
  next: 0
  next_extras: 0
  next_jsonapi: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  quickedit: 0
  rdf: 0
  search: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  subrequests: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  views_ui: 0
  pathauto: 1
  content_translation: 10
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
