_core:
  default_config_hash: yTxtFqBHnEWxQswuWvkjE8mKw2t8oKuCL1q8KnfHuGE
langcode: en
uuid: 1a7d2047-f4dc-4686-a2df-c4ef2172df43
name: 'Next.js for Drupal'
mail: admin@example.com
slogan: ''
page:
  403: ''
  404: ''
  front: /node/6
admin_compact_mode: false
weight_select_max: 100
default_langcode: en
mail_notification: ''
