name: next
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  phpunit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Supported PHP versions: https://www.drupal.org/docs/getting-started/system-requirements/php-requirements
        php: ["8.1", "8.2"]
        # Supported Drupal versions: https://www.drupal.org/project/drupal
        drupal: ["10.0", "10.1"]
    name: Drupal ${{ matrix.drupal }} - PHP ${{ matrix.php }}
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: db
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pdo, mysql, pdo_mysql, bcmath, soap, intl, gd, exif, iconv
          coverage: none
          tools: composer:v2
      - name: Get composer cache directory
        id: composercache
        run: |
          cd modules/next
          echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache@v3
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.drupal }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.drupal }}-composer-
      - name: Setup problem matchers for PHPUnit
        run: echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Setup Drupal
        run: |
          COMPOSER_MEMORY_LIMIT=-1 composer create-project drupal/recommended-project:${{ matrix.drupal }}.x ~/drupal --no-interaction --no-install
          cd ~/drupal
          composer config extra.enable-patching true
          composer config extra.compile-mode all
          composer config minimum-stability dev
          composer config prefer-stable true
          composer config preferred-install dist
          composer config repositories.0 path $GITHUB_WORKSPACE
          composer config repositories.1 composer https://packages.drupal.org/8
          composer config allow-plugins true -n
          COMPOSER_MEMORY_LIMIT=-1 composer require drupal/core-dev --no-install
          composer install
      - name: Add phpspec/prophecy-phpunit
        run: |
          cd ~/drupal
          COMPOSER_MEMORY_LIMIT=-1 composer require --dev phpspec/prophecy-phpunit:^2 -W
        if: ${{ startsWith(matrix.drupal, '9') }}
      - name: Run phpcs
        run: |
          ~/drupal/vendor/bin/phpcs -p -s --colors --standard=modules/next/phpcs.xml modules/next
      - name: Copy module
        run: cp -R ../next-drupal/modules/next ~/drupal/web/modules/next
      - name: Run php built-in server
        run: php -S 127.0.0.1:8080 -t ~/drupal/web &
      - name: Run PHPUnit
        run: |
          cd ~/drupal/web
          ../vendor/bin/phpunit -c core modules/next
        env:
          SYMFONY_DEPRECATIONS_HELPER: weak
          SIMPLETEST_DB: mysql://root:@127.0.0.1:${{ job.services.mysql.ports[3306] }}/db
          SIMPLETEST_BASE_URL: http://127.0.0.1:8080
